FROM gocd/gocd-agent-centos-7:v19.5.0

RUN yum install -y awscli

# install nodejs
RUN yum install -y gcc-c++ make
RUN curl -sL https://rpm.nodesource.com/setup_12.x | bash -
RUN yum install -y nodejs

# install terraform
RUN yum update -y
RUN yum install -y wget unzip
RUN wget https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
RUN unzip ./terraform_0.12.3_linux_amd64.zip -d /usr/local/bin/